### ISSUE TITLE
Koodikatselmointi#1

### ISSUE THREAD

**Issue by vihaton** [rojokela/Peliarpoja#1]
**Annan yksityiskohtaisempaa palautetta, kun viikon kolme palautus on tehty.**

Sitä odotellessa totean vain, että tähän mennessä näyttää hyvältä ja selkeältä. :+1:

**Comment by rojokela** [comment]
Ei mulla tältä viikolta tuu mitää ku oon ollu niin laiska. Voit laittaa tosta vähästä mitä tuolla ny on, kommenttii mut ei siitä paljoo mitää voi sanoo ku niin vähän vasta tehty mitää.
